services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
  localstack:
    image: localstack/localstack:s3-latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  poc-parquet:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - localstack  
    container_name: poc-parquet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AWS_S3_ENDPOINT=http://localstack:4566
